version: "3"
services:
  todolistdbtest:
    container_name: todolistdbtest
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - shared-network
  
networks:
  shared-network: