version: "3"
services:
  todolistdb:
    container_name: todolistdb
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - shared-network

  todolist:
      container_name: todolist
      build:
        context: .
        dockerfile: Dockerfile.develop
      ports:
        - "4000:4000"
      depends_on:
        - todolistdb
      volumes:
        - /data/postgres:/data/postgres
      networks:
        - shared-network
  
networks:
  shared-network: